version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:654654184498:task-definition/asc-api-service:12"
        LoadBalancerInfo:
          ContainerName: "asc-api-service"
          ContainerPort: 80
